'use client';
import {Cite} from './references';
import { useState } from 'react';
import katex from 'katex';
import mug from './mug-measurements.json';
import { ArrowRight, ArrowUpRight, LockKeyhole, Scan } from 'lucide-react';
import { Switch } from '@/components/ui/switch';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell, TableCaption } from '@/components/ui/table';
import {contexts,score,effects,additiveScore,observedScore,interaction,suitcaseShapley} from './interaction-example';
function MathBlock({tex}:{tex:string}) {return <div className="lesson-math" dangerouslySetInnerHTML={{__html:katex.renderToString(tex,{displayMode:true,output:'htmlAndMathml',throwOnError:true,trust:false,strict:'error'})}}/>}
const signs=(v:number,digits=3)=>(v>=0?'+':'−')+Math.abs(v).toFixed(digits);
const regionIds=['target_part','source_part','object_remainder'] as const;
function value(indices:number[]){const key=indices.length?'visible_'+[...indices].sort().map(i=>regionIds[i]).join('__'):'visible_none';return mug.coalition_scores[key as keyof typeof mug.coalition_scores].yes_minus_no_margin;}
export default function MethodWalkthrough(){
 const [restored,setRestored]=useState(true);
 const before=value([0,2]),after=value([0,1,2]);
 const [couchVisible,setCouchVisible]=useState(false);
 const selected=couchVisible?1:0;
 const current=contexts[selected];
 return <section id="method" className="method-section"><div className="wrap lesson">
 <div className="section-heading"><div><div className="eyebrow">HOW REGIONTRACE WORKS</div><h2>Follow the evidence, one comparison at a time.</h2></div></div>
 <p className="lesson-lead">Start with the mug to understand a single Region Effect. Then use a two-object example to see interaction and Shapley weighting in action.</p>
 <article id="method-target" className="lesson-step">
 <div className="lesson-step-title"><span>01</span><div><h3>One answer. Different visual evidence.</h3><p>Start with the mug above. We track support for the model’s answer, even when it is wrong.</p></div></div>
 <div className="fixed-question"><div><small>QUESTION</small><p>{mug.question}</p></div><div><small>FIXED TARGET</small><strong>Yes <em>Incorrect answer</em></strong></div></div>
 <div className="fixed-rules"><LockKeyhole size={16}/><span>Same question</span><span>Same textual prefix</span><span>Same target answer</span><b>Only region visibility changes</b></div>
 <p className="lesson-note">Define meaningful, non-overlapping regions: here, the rim, body, and remaining parts. Regions may come from annotations, drawings, or segmentation. Hidden regions are replaced by a baseline; pixels outside the selected regions stay unchanged.</p>
 </article>
 <article id="method-effect" className="lesson-step">
 <div className="lesson-step-title"><span>02</span><div><h3>Restore a region. Measure the difference.</h3><p>Keep the rim and remainder visible. Compare the same Yes before and after restoring the body.</p></div></div>
 <div className="restore-comparison">
 <figure className={!restored?'chosen':''}><div className="comparison-label">BEFORE <span>Body hidden</span></div><img src="assets/mug-source_removed.png" alt="Mug scene with only the body replaced by the baseline; rim and remainder stay visible"/><figcaption><span>Yes–No log-score margin</span><strong>{signs(before,2)}</strong></figcaption></figure>
 <div className="restore-arrow"><ArrowRight size={25}/><span>Restore<br/>the body</span></div>
 <figure className={restored?'chosen':''}><div className="comparison-label">AFTER <span>Body restored</span></div><img src="assets/mug-full.png" alt="The same mug scene with the body restored"/><figcaption><span>Yes–No log-score margin</span><strong>{signs(after,2)}</strong></figcaption></figure>
 </div>
 <div className="restore-control"><label htmlFor="restore-mug">Restore the body <Switch id="restore-mug" checked={restored} onCheckedChange={setRestored}/></label><p aria-live="polite">Current score: <b>{signs(restored?after:before,2)}</b> · Constrained answer: <b>{restored?'Yes':'No'}</b></p></div>
 <div className="lesson-equation"><MathBlock tex={String.raw`E_{\mathrm{body},d}(S)=\underbrace{V_d(S\cup\{\mathrm{body}\})}_{\text{body restored}}-\underbrace{V_d(S)}_{\text{body hidden}}`}/><div className="equation-result"><span>THIS COMPARISON</span><strong>+3.75 − (−1.25) = <b>+5.00</b></strong><p>Restoring the body supports the incorrect Yes in this context.</p></div></div>
 <div className="sign-guide"><div><b>+ Positive</b><p>The restored region supports the target.</p></div><div><b>− Negative</b><p>The restored region suppresses the target.</p></div><div><b>≈ Near zero</b><p>The region makes little difference in this context.</p></div></div>
 <Accordion className="lesson-details"><AccordionItem value="score"><AccordionTrigger>What exactly is the score?</AccordionTrigger><AccordionContent><p>Here, S is the set of other visible regions: the rim and remainder. The fixed target d is Yes. We use the log-score difference between Yes and No; higher values favor Yes.</p><MathBlock tex={String.raw`V_{\mathrm{YN}}(S)=\log p_\theta(\mathrm{Yes}\mid q,I_S,p)-\log p_\theta(\mathrm{No}\mid q,I_S,p)`}/><p>The question q and saved textual prefix p stay fixed while the image changes to Iₛ. This example has no generated explanation. A Region Effect of +5.00 is a change in this log-score margin, not five percentage points and not a correctness score.</p><p>Measurements: InternVL3-8B, PACO image 498134, processor-mean baseline. This is the development example in Figure 2, separate from the frozen evaluation cohort.</p><a href="assets/mug-measurements.json" download>Download the underlying measurements</a></AccordionContent></AccordionItem></Accordion>
 </article>
 <article id="method-interaction" className="lesson-step">
 <div className="lesson-step-title"><span>03</span><div><h3>Object interactions and Shapley-weighted effects.</h3><p>A second example makes the interaction clearer: how does the couch change the suitcase’s contribution, and how does Shapley summarize it?</p></div></div>
 <div className="fixed-question"><div><small>NEW EXAMPLE · COCO 81061 · INTERNVL3-8B</small><p>Is the suitcase in front of the couch?</p></div><div><small>FIXED TARGET</small><strong>Yes</strong></div></div>
 <p className="lesson-note">Only suitcase and couch are selected for this example. The chair and all other background pixels stay visible and unchanged. Toggle the couch; within each image pair, only the suitcase is restored.</p>
 <div className="interaction-toggle"><label htmlFor="method-couch">Keep the couch visible <Switch id="method-couch" checked={couchVisible} onCheckedChange={setCouchVisible}/></label><span>The background stays fixed.</span></div>
 <div className="restore-comparison">
 <figure><div className="comparison-label">BEFORE <span>Suitcase hidden</span></div><img src={`assets/${current.before}.png`} alt={`Suitcase hidden; couch ${couchVisible?'visible':'hidden'}; chair and background unchanged`}/><figcaption><span>Yes–No log-score margin</span><strong>{signs(score(current.before))}</strong></figcaption></figure>
 <div className="restore-arrow"><ArrowRight size={25}/><span>Restore<br/>the suitcase</span></div>
 <figure className="chosen"><div className="comparison-label">AFTER <span>Suitcase restored</span></div><img src={`assets/${current.after}.png`} alt={`Suitcase restored; couch ${couchVisible?'visible':'hidden'}; chair and background unchanged`}/><figcaption><span>Yes–No log-score margin</span><strong>{signs(score(current.after))}</strong></figcaption></figure>
 </div>
 <div className="interaction-contexts" aria-label="Compare the suitcase effect across contexts">{contexts.map((c,i)=><button key={c.label} aria-pressed={i===selected} className={i===selected?'active':''} onClick={()=>setCouchVisible(i===1)}><span>{c.label}</span><strong>{signs(effects[i])}</strong><div className="effect-meter"><i style={{width:`${effects[i]/8*100}%`}}/></div><small>Suitcase’s Region Effect</small></button>)}</div>
 <div className="shapley-takeaway"><Scan size={20}/><p><strong>The couch changes the suitcase’s effect by {signs(interaction)}.</strong> This difference is the conditional interaction between the two selected objects on the fixed Yes–No log-score scale. A larger effect means stronger support for Yes, not greater correctness.</p></div>
 <Accordion className="lesson-details"><AccordionItem value="effect"><AccordionTrigger>How are the effect and interaction calculated?</AccordionTrigger><AccordionContent><MathBlock tex={String.raw`E_{s,d}(S)=V_d(S\cup\{s\})-V_d(S)`}/><p>Here s is the suitcase, c is the couch, and S is either the empty set or the couch. Empty means both selected objects are hidden; the fixed background is still visible. The question, prefix, and target Yes stay unchanged.</p><MathBlock tex={String.raw`J_{s,c}=E_{s,d}(\{c\})-E_{s,d}(\varnothing)=6.750-1.625=5.125`}/><p>The score is the log-score margin between Yes and No. Hidden objects use the processor-mean baseline. These differences are not percentage points, and there is no generated explanation at this checkpoint.</p><a href="assets/two-object-interaction.json" download>Download the four measured scores and derived results</a></AccordionContent></AccordionItem></Accordion>
 <div id="interaction-reference" className="interaction-reference"><div><div className="eyebrow">MAKE THE INTERACTION VISIBLE</div><h4>What would simple addition predict?</h4><p>Start from the score with both objects hidden. Add the suitcase-only effect and the couch-only effect. This gives an additive reference: what the joint score would be if the objects had no interaction on this score scale.</p></div><div className="interaction-reference-chart"><div className="reference-row"><span>No-interaction reference <small>Derived, not a separate model run</small></span><strong>{signs(additiveScore)}</strong><div className="reference-meter"><i style={{width:`${additiveScore/8*100}%`}}/></div></div><div className="reference-row observed"><span>Both objects visible <small>Measured joint score</small></span><strong>{signs(observedScore)}</strong><div className="reference-meter"><i style={{width:`${observedScore/8*100}%`}}/></div></div><p className="interaction-gap">Observed − additive reference <b>{signs(interaction)}</b></p></div></div>
 <MathBlock tex={String.raw`\underbrace{-2.000}_{\text{baseline}}+\underbrace{1.625}_{\text{suitcase alone}}+\underbrace{2.625}_{\text{couch alone}}=\underbrace{2.250}_{\text{additive reference}}\quad\neq\quad\underbrace{7.375}_{\text{measured together}}`}/>
 <p className="lesson-note">“No interaction” is a mathematical reference, not another image condition or a claim that a different model was tested. The observed excess of +5.125 is specific to these regions, this fixed background, and this score.</p>
 <h4 id="shapley-summary">Summarize both contexts with Shapley weights.</h4>
 <div className="shapley-intro"><div><span>WHY SHAPLEY?</span><h4>Which effect should represent the suitcase?</h4><p>Only reporting +1.625 misses the strong support available with the couch. Only reporting +6.750 describes the couch-visible condition. The two measurements answer different conditional questions.</p></div><div><span>WHAT IS SHAPLEY?</span><h4>A weighted average over region subsets.<Cite id="shapley"/></h4><p>Measure the suitcase’s effect for every subset of the other selected regions, then apply Shapley weights. With only two selected objects, there are two contexts—couch hidden or visible—and each receives weight ½.</p></div></div>
 <div className="shapley-comparison">
 <div className="single-effect-panel"><div className="comparison-kicker">ONE SELECTED CONTEXT</div><h4>Region Effect</h4><p className="shapley-question">How much does restoring the suitcase add <em>here</em>?</p><div className="context-choices"><label htmlFor="shapley-couch">Couch visible <Switch id="shapley-couch" checked={couchVisible} onCheckedChange={setCouchVisible}/></label></div><div className="single-score-pair" aria-live="polite"><div><span>Suitcase hidden</span><strong>{signs(score(current.before))}</strong></div><ArrowRight size={19}/><div><span>Suitcase restored</span><strong>{signs(score(current.after))}</strong></div></div><div className="single-effect-result" aria-live="polite"><span>Suitcase’s effect · {current.label.toLowerCase()}</span><strong>{signs(effects[selected])}</strong><div className="effect-meter"><i style={{width:`${effects[selected]/8*100}%`}}/></div></div><p className="shapley-panel-note">The value changes with the selected context. The matching row is highlighted on the right.</p></div>
 <div className="shapley-summary-panel"><div className="comparison-kicker">ALL CONTEXTS · SHAPLEY WEIGHTS</div><h4>Shapley-averaged Region Effect</h4><p className="shapley-question">What is the suitcase’s <em>weighted contribution</em>?</p>
 <Table className="subset-table"><TableCaption>Each row is a region subset, not a step in a reveal sequence. All effects use the same target Yes.</TableCaption><TableHeader><TableRow><TableHead>Other regions<br/>visible</TableHead><TableHead>Effect</TableHead><TableHead>Weight</TableHead><TableHead>Weighted<br/>effect</TableHead></TableRow></TableHeader><TableBody>{contexts.map((c,i)=><TableRow key={c.label} data-state={i===selected?'selected':undefined}><TableCell><button className="subset-context-button" aria-pressed={i===selected} onClick={()=>setCouchVisible(i===1)}>{i===0?'None (∅)':'Couch'}</button></TableCell><TableCell>{signs(effects[i])}</TableCell><TableCell>½</TableCell><TableCell>{signs(effects[i]*c.weight,4)}</TableCell></TableRow>)}</TableBody></Table>
 <div className="shapley-average-result"><div><span>Sum of weighted effects</span><strong>{signs(suitcaseShapley,4)}</strong></div><span className="average-badge">Fixed across both contexts</span></div><p className="shapley-panel-note">The suitcase’s Shapley value includes its stand-alone effect plus half of the interaction. It summarizes the same measured data; it does not remove the interaction.</p></div></div>
 <div className="shapley-calculation"><span>CONTEXTS · WEIGHTS · WEIGHTED SUM</span><MathBlock tex={String.raw`\phi_s=\tfrac12\times1.625+\tfrac12\times6.750=4.1875`}/></div>
 <div className="interaction-allocation"><h4>Where does the interaction go?</h4><p>With two selected regions, Shapley splits the interaction equally between them.</p><div><span>Suitcase</span><MathBlock tex={String.raw`\phi_s=\underbrace{1.625}_{\text{stand-alone effect}}+\underbrace{\tfrac12(5.125)}_{\text{interaction share}}=4.1875`}/></div><div><span>Couch</span><MathBlock tex={String.raw`\phi_c=\underbrace{2.625}_{\text{stand-alone effect}}+\underbrace{\tfrac12(5.125)}_{\text{interaction share}}=5.1875`}/></div><p>The two contributions sum to +9.375: the observed change from both selected objects hidden (−2.000) to both visible (+7.375).</p></div>
 <Accordion className="lesson-details"><AccordionItem value="shapley"><AccordionTrigger>General formula: more than two selected regions</AccordionTrigger><AccordionContent><MathBlock tex={String.raw`\phi_{i,d}=\sum_{S\subseteq N\setminus\{i\}}\underbrace{\frac{|S|!\,(K-|S|-1)!}{K!}}_{\text{Shapley weight}}\,\underbrace{\big[V_d(S\cup\{i\})-V_d(S)\big]}_{\text{effect in context }S}`}/><p>N indexes the K selected regions. S is a subset of the other selected regions. The weight depends on the size of that subset. For K = 2 the two weights are ½ and ½. For K = 3, the empty, two single-region, and full contexts have weights ⅓, ⅙, ⅙, and ⅓; a plain average of the four contexts would be different.</p><MathBlock tex={String.raw`\sum_{i=1}^{K}\phi_{i,d}=V_d(N)-V_d(\varnothing)`}/><p>Exact enumeration evaluates all 2ᴷ image subsets independently and reuses their scores. No sequential restoration run is required. The context-specific effects remain available so that a summary does not hide interaction.</p><p>The demonstration above conditions on the chair being visible and selects only suitcase and couch. It is a derived two-region game from the saved COCO experiment, not the three-region Shapley value reported in Figure 1.</p></AccordionContent></AccordionItem></Accordion>
 </article>
 <div className="interpretation"><Scan size={23}/><div><h4>Read the effect within its measurement conditions.</h4><p>RegionTrace measures conditional answer support. It depends on the regions, replacement baseline, prefix, target, and scoring rule. It does not identify attention allocation, a unique internal mechanism, or the total causal effect on a freely regenerated answer.</p></div></div>
 </div></section>;
}
